#!/usr/bin/perl -w

my $longest = 0;

foreach my $key ( keys %ENV ) {
	
	if ( length( $key ) > $longest ) {

		$longest = length ( $key );
	}
}

foreach my $key (sort keys %ENV) {

	printf "%-${longest}s %s \n", $key, $ENV{$key};
}
