#!/usr/bin/perl -w

# make a report of the access and modification itmes (in the epoch time) of the files in the current directory.

foreach( glob ('*') ) {
    my ( $atime, $mtime ) = map {
        my ( $year, $month, $day ) = (localtime($_))[5, 4, 3];
        $year += 1900;
        $month += 1;
        sprintf '%4d-%02d-%02d', $year, $month, $day;
    } (stat) [8, 9];

    printf "%-20s %10s %10s\n", $_, $atime, $mtime;
}
