#!/usr/bin/perl -w

# make a report of the access and modification itmes (in the epoch time) of the files in the current directory.

foreach( glob ('*') ) {
    my ( $atime, $mtime ) = (stat)[8, 9];
    printf "%-20s %10d %10d\n", $_, $atime, $mtime;
}
