#!/usr/bin/perl -w

print "input the first num:\n";
chomp($num1 = <STDIN>);

print "input the second num:\n";
chomp($num2 = <STDIN>);

$result = $num1 * $num2;
print "The product of $num1 and $num2 is $result\n";
