#!/usr/bin/perl
while (<>) {                   # take one input line at a time
	chomp;
	if (/(?<word>\b\w*a\b)/) {	#\b matches at either end of a word.
		print "Matched: $`<$&>$'\n";  # the special match vars
		print "Matched: \'$+{word}\'\n";
	} else {
		print "No match: |$_|\n";
	}
}
