#!/usr/bin/perl
while (<>) {                   # take one input line at a time
	chomp;
	if (/a\b/) {	#\b matches at either end of a word.
		print "Matched: |$`<$&>$'|\n";  # the special match vars
	} else {
		print "No match: |$_|\n";
	}
}
