#!/usr/bin/perl
while (<>) {                   # take one input line at a time
	chomp;
	if (/(\b\w*a\b)(.{0,5})/s) {	#\s makes "." matches any character
		print "Matched: $`<$&>$'\n";  # the special match vars
		print "Matched: \'$1'\n";
		print "Matched: \'$2'\n";
	} else {
		print "No match: |$_|\n";
	}
}
