#!/usr/bin/perl -w

#Install Module::CoreList module, and print a list of all of the modules that came with Perl 5.14

use Module::CoreList;

my %modules = %{ $Module::CoreList::version{5.014} };

#foreach my $key ( sort keys %modules) {

#	print "$key \n";
#}

print join "\n", keys %modules;
