#!/usr/bin/perl -w

use strict;

sub total {

	my @numbers = @_;
	my $sum = 0;

	foreach my $temp ( @numbers ) {

		$sum += $temp;
	}

	$sum;
}



my @list = 1..1000;
my $total_count = total(@list);
print "The total from 1 to 1000 is $total_count.\n";
